print('X' * 5)
print('X   X')
print('X   X')
print('X   X')
print('X' * 5)

print('\n\n')
print('ALUNO(A)        NOTA')
print('='*9,'    ','='*5)
print('ALINE           9,0')
print('MÁRIO           DEZ')
print('SÉRGIO          4,5')
print('SHIRLEY         7,0')

print('\n\n')
print('P'*5)
print('P    P')
print('P     P')
print('P   P')
print('P')
print('P')
print('P')

print('\n\n')
print('          *          ')
print('         XXX         ')
print('       XOXXXOX       ')
print('     XXXXXOXXXX      ')
print('    XXOXXXXXOXXX     ')
print('   XXXOXXXXXOXXXX    ')
print('  XXXOXXXXXOXXXXXX   ')
print('         XX          ')
print('         XX          ')
print('      OO XX OO       ')