n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
print('Soma: {} + {} = {}'.format(n1, n2, n1+n2))
print('Subtração: {} - {} = {}'.format(n1, n2, n1-n2))
print('Multiplicação: {} * {} = {}'.format(n1, n2, n1*n2))
print('Divisão: {} / {} = {}'.format(n1, n2, n1/n2))
print('Exponenciação: {} ** {} = {}'.format(n1, n2, n1**n2))
print('Resto da divisão: {} % {} = {}'.format(n1, n2, n1%n2))